### ISSUE TITLE
Can't log in with Steam Mobile Authenticator

### ISSUE THREAD

**Issue by Toaaa** [DrWarpMan/steam-hour-booster#4]
I have filled in my `config.json` and run the hour booster. It loads for a second and then it says `InvalidPassword`. I use the Steam Mobile Authenticator but I have not received a login authorization request on my phone.

```bash
root@gh:/opt/steam-hour-booster# bun .
[toaaadsttd] Logging in...
830 |
831 |                   default:
832 |                           // server is up, so reset logon timer
833 |                           delete this._logonTimeoutDuration;
834 |
835 |                           let error = new Error(EResult[body.eresult] || body.eresult);
                      ^
error: InvalidPassword
      at /opt/steam-hour-booster/node_modules/steam-user/components/09-logon.js:835:17
      at _handleLogOnResponse (/opt/steam-hour-booster/node_modules/steam-user/components/09-logon.js:700:29)
      at /opt/steam-hour-booster/node_modules/steam-user/components/09-logon.js:452:16

Bun v1.1.22-canary.96+df33f2b2a (Linux x64)
```

**Comment by DrWarpMan** [comment]
Hi, have you tried to run this on an account without Steam Guard? Does that work fine?
Also, if it wouldn't be much trouble, you could try removing Steam Guard completely and see if Steam Guard is really the issue (I understand if you don't wanna try that).

I am using this myself on accounts with and without Steam Guard (with either e-mail or mobile authenticator) and they work fine.

Either way, are you 100% sure you are using a correct password, cause I don't think you would be getting **InvalidPassword** error, but I might be wrong hence Steam API sometimes works in mysterious ways and things are often not well documented.

**Comment by Toaaa** [comment]
Hi, I just tried another account that also uses Steam Mobile Authenticator, and that account works just fine.

```
root@gh:/opt/steam-hour-booster# bun .
[toaaadsttdsmurf] Logging in...
[toaaadsttdsmurf] Steam Guard code: 
```

I double checked the password and username on both accounts. The only logical explanation I can think of is that the password of the first account is too long for the steam hour booster (which would be weird). I can log in with both accounts in the Steam client and on the Steam website, so the problem must be either in the code or in the Steam API.

**Comment by DrWarpMan** [comment]
Can you run the following script with Bun and see if you can login when using just the [node-steam-user](https://github.com/DoctorMcKay/node-steam-user) library? (Replace with your own credentials.)
```js
import Steam from "steam-user";

const steam = new Steam({
    dataDirectory: "./data", // remove the directory after testing
});

steam.logOn({
    accountName: "username",
    password: "password"
});
```
_(Since you are using Bun, steam-user should get automatically downloaded.)_

If you still can not login, you should probably write an issue on the library's github page.

**Comment by Toaaa** [comment]
Hi. I just changed the password of my first account and shortened it a bit, and now it works. Either the password was too long for the hour booster or I just had to change it once. Either way, it works now.

**Comment by DrWarpMan** [comment]
Also you could try running it with Node.

> Hi. I just changed the password of my first account and shortened it a bit, and now it works. Either the password was too long for the hour booster or I just had to change it once. Either way, it works now.

Glad you got it working, how long was your password exactly if you don't mind sharing?

**Comment by Toaaa** [comment]
> Glad you got it working, how long was your password exactly if you don't mind sharing? Or maybe it contained some weird symbols? It's really weird.

My previous password was 128 characters long and contained `A-Z`, `a-z`, `0-9` and `!@#$%^&*` characters.

Here is my previous password for the first steam account:
```
nZG%nE3zo9@R7&5vh#cRkQ$Lc39D!^xeW^GH5^wP#9SwRvGYLC*TyomTrQhn8T&2pbahLt%yCKQ2BFHHAZG$R&S$#*pmRe&JN$tU3K2A*J#HSJPuQek@iV2Q5Bj!y3nh
```

**Comment by DrWarpMan** [comment]
The limit is apparently 64 characters. Passwords with length over 64 will not work and produce InvalidPassword error.
It seems to be an issue in the Steam library I am using, I will try to investigate and report back if I find anything.

Upstream: https://github.com/DoctorMcKay/node-steam-session/issues/48
