### ISSUE TITLE
Tried creating a stack with portainer and got this error

### ISSUE THREAD

**Issue by TomerGamerTV** [DrWarpMan/steam-hour-booster#6]
I am getting this error in the console:

`533B/533B a257f545a1ba Pull complete booster Pulled Network steam-hour-booster_default Creating Network steam-hour-booster_default Created Container steam-hour-booster Creating Container steam-hour-booster Created Container steam-hour-booster Starting Error response from daemon: Bind mount failed: '/data/compose/3/tokens' does not exists
`

Also, can you tell me how the folder structure is supposed to look? I'm on a NAS and it's a bit complicated...

**Comment by DrWarpMan** [comment]
I am not sure what the error refers to exactly. I don't have enough experience with Portainer and definitely not NAS.
Could it be that your directory `/data/compose/3/tokens` does not exist on host?

The folder structure inside the image is described in the example [docker-compose.yml](https://github.com/DrWarpMan/steam-hour-booster/blob/24691b82d612104426c079bb09a140b7c8779d66/docker-compose.yml):
```
/app/steam-data
/app/config.json
/app/tokens
```

So, you should mount these files/directories to your host.

**Comment by DrWarpMan** [comment]
`steam-data` and `tokens` are folders, `config.json` is a file

**Comment by TomerGamerTV** [comment]
> `steam-data` and `tokens` are folders, `config.json` is a file

Does everything need to be in an app folder?
Like: 
/app/steam-data
/app/tokens
/app/config.json

**Comment by TomerGamerTV** [comment]
It just keeps throwing me these errors
![image](https://github.com/user-attachments/assets/bf956613-247f-4111-821b-4871d0e71d80)

**Comment by TomerGamerTV** [comment]
Tried running it in an ubuntu docker vm and got this error after logging in:


```
221 |           delete this._messageLength;
222 |           if (this.sessionKey) {
223 |                   try {
224 |                           message = SteamCrypto.symmetricDecrypt(message, this.sessionKey, true);
225 |                   } catch (ex) {
226 |                           this._fatal(new Error('Encrypted message authentication failed'));
                      ^
error: Encrypted message authentication failed
      at _readMessage (/root/steam-hour-booster/node_modules/steam-user/components/connection_protocols/tcp.js:226:17)
      at emit (node:events:183:48)
      at emitReadable_ (node:stream:1842:27)

[tomertv] Logging out...
3116 | export default "node:crypto";
                         ^
error: unable to decrypt data
      at unpad (node:crypto:3116:19)
      at node:crypto:1223:46
      at final (node:stream:3246:19)
      at prefinish (node:stream:3264:23)
      at emit (node:events:183:48)
      at prefinish (node:stream:2799:23)
      at finishMaybe (node:stream:2806:25)
      at afterWrite (node:stream:2675:24)
      at onwrite (node:stream:2640:21)
      at node:stream:3284:44

Bun v1.1.30 (Linux x64 baseline)
```

**Comment by DrWarpMan** [comment]
I am not  really sure what is the reason behind this, as I am not able to replicate it.

Another user was reporting it [here](https://github.com/DrWarpMan/steam-hour-booster/issues/2#issuecomment-1872252296), but they claim that the booster works even through the error.

**Comment by TomerGamerTV** [comment]
I tried with the .env file too but it didn’t help.

I’m using the docker compose file you provide in docker url inside the
readme, I can record a video of trying to deploy it if you want

**Comment by DrWarpMan** [comment]
You may also try to run the following script with Bun:

```ts
// test.js
import Steam from "steam-user";

const steam = new Steam({
    dataDirectory: "./data", // remove the directory after testing
    protocol: Steam.EConnectionProtocol.TCP
});

steam.logOn({
    accountName: "your_username",
    password: "your_password"
});

steam.on("loggedOn", () => {
    console.log("Logged in");
})

steam.gamesPlayed([730]); // currently, CS:GO - replace with the exact game list that you specified when running 'steam-hour-booster'
```

**Comment by TomerGamerTV** [comment]
Make a new test.js file and try running that? Also how to I run a separate
script with bun?

**Comment by DrWarpMan** [comment]
Just create a new file called `test.js`, inside that "ubuntu docker vm".
Put the script I posted inside the file, replace username & password, run:
```bash
bun test.js
```

**Comment by TomerGamerTV** [comment]
> Just create a new file called `test.js`, inside that "ubuntu docker vm". Put the script I posted inside the file, replace username & password, run:
> 
> ```shell
> bun test.js
> ```

Still same error:
```
221 |           delete this._messageLength;
222 |           if (this.sessionKey) {
223 |                   try {
224 |                           message = SteamCrypto.symmetricDecrypt(message, this.sessionKey, true);
225 |                   } catch (ex) {
226 |                           this._fatal(new Error('Encrypted message authentication failed'));
                      ^
error: Encrypted message authentication failed
      at _readMessage (/root/steam-hour-booster/node_modules/steam-user/components/connection_protocols/tcp.js:226:17)
      at emit (node:events:183:48)
      at emitReadable_ (node:stream:1842:27)
3116 | export default "node:crypto";
                         ^
error: unable to decrypt data
      at unpad (node:crypto:3116:19)
      at node:crypto:1223:46
      at final (node:stream:3246:19)
      at prefinish (node:stream:3264:23)
      at emit (node:events:183:48)
      at prefinish (node:stream:2799:23)
      at finishMaybe (node:stream:2806:25)
      at afterWrite (node:stream:2675:24)
      at onwrite (node:stream:2640:21)
      at node:stream:3284:44

Bun v1.1.30 (Linux x64 baseline)
```

Im trying these IDs:
"games": [1849000,1944240]

**Comment by DrWarpMan** [comment]
Okay, one last thing, could you test the following?
1. Install `node` (if its not already installed) within the Ubuntu container
2. Create a new directory (`foobar`) anywhere, with the following structure:
```
foobar/
foobar/package.json
foobar/test.js
```
3. Put the following inside `package.json`:
```json
{
  "dependencies": {
    "steam-user": "^5.2.0"
  },
  "type": "module"
}
```
4. Run  `npm install` from within the `foobar` directory.
5. Run `node test.js`

And report back whether the error occurs.

**Comment by TomerGamerTV** [comment]
Alr after logging in nothing happens, it didn't crash but it doesn't look like it is farming anything

**Comment by DrWarpMan** [comment]
> Okay, one last thing, could you test the following?
> 
> 1. Install `node` (if its not already installed) within the Ubuntu container
> 2. Create a new directory (`foobar`) anywhere, with the following structure:
> 
> ```
> foobar/
> foobar/package.json
> foobar/test.js
> ```
> 
> 3. Put the following inside `package.json`:
> 
> ```json
> {
>   "dependencies": {
>     "steam-user": "^5.2.0"
>   },
>   "type": "module"
> }
> ```
> 
> 4. Run  `npm install` from within the `foobar` directory.
> 5. Run `node test.js`
> 
> And report back whether the error occurs.

@TomerGamerTV you did these exact steps, launched `node test.js`, and it printed `"Logged in"`?

**Comment by TomerGamerTV** [comment]
> > Okay, one last thing, could you test the following?
> > 
> > 1. Install `node` (if its not already installed) within the Ubuntu container
> > 2. Create a new directory (`foobar`) anywhere, with the following structure:
> > 
> > ```
> > foobar/
> > foobar/package.json
> > foobar/test.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Put the following inside `package.json`:
> > 
> > ```json
> > {
> >   "dependencies": {
> >     "steam-user": "^5.2.0"
> >   },
> >   "type": "module"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Run  `npm install` from within the `foobar` directory.
> > 5. Run `node test.js`
> > 
> > And report back whether the error occurs.
> 
> @TomerGamerTV you did these exact steps, launched `node test.js`, and it printed `"Logged in"`?

Yep I followed everything you said, logged in and then nothing happens

**Comment by DrWarpMan** [comment]
Okay, so if what you are saying is true, then the 'encryption error' is related to Bun.

Now, I can't see why the farming would not work for you. Is there any chance you could give me your Discord perhaps, for  faster communication?

**Comment by TomerGamerTV** [comment]
> Okay, so if what you are saying is true, then the 'encryption error' is related to Bun.
> 
> Now, I can't see why the farming would not work for you. Is there any chance you could give me your Discord perhaps, for faster communication?

yea, same user as here. send me a friend req

**Comment by DrWarpMan** [comment]
After a debug session with @TomerGamerTV outside of GitHub, it seems the reason for this is Bun's incompatibility with Node's `crypto` module. Unfortunately I am unable to reproduce it, so I can't even try to take a closer look at a possible workaround/solution. The only "hint" I got is that it's related to different Steam account's settings - specifically Family Sharing.
